### ISSUE TITLE
udev rules have invalid substitution syntax

### ISSUE THREAD

**Issue by mike-silva** [RPi-Distro/pi-bluetooth#27]
On Pi 4b running Ubuntu 21.04 and pi-bluetooth/hirsute,now 0.1.15ubuntu2 arm64 the following warnings appear at boot:

systemd-udevd[976]: /usr/lib/udev/rules.d/90-pi-bluetooth.rules:14 Invalid value "/bin/sh -c 'ALIASES=/proc/device-tree/aliases; if cmp -s $ALIASES/uart0 $ALIASES/serial0; then echo 0;elif cmp -s $ALIASES/uart0 $ALIASES/serial1; then echo 1; else exit 1; fi'" for PROGRAM (char 58: invalid substitution type), ignoring, but please fix it.

systemd-udevd[976]: /usr/lib/udev/rules.d/90-pi-bluetooth.rules:27 Invalid value "/bin/sh -c 'ALIASES=/proc/device-tree/aliases; if [ -e /dev/ttyAMA0 ]; then exit 1; elif cmp -s $ALIASES/uart0 $ALIASES/serial0; then echo 0;elif cmp -s $ALIASES/uart0 $ALIASES/serial1; then echo 1; else exit 1; fi'" for PROGRAM (char 97: invalid substitution type), ignoring, but please fix it.

systemd-udevd[976]: /usr/lib/udev/rules.d/90-pi-bluetooth.rules:38 Invalid value "/bin/sh -c 'ALIASES=/proc/device-tree/aliases; if cmp -s $ALIASES/uart1 $ALIASES/serial0; then echo 0; elif cmp -s $ALIASES/uart1 $ALIASES/serial1; then echo 1; else exit 1; fi '" for PROGRAM (char 58: invalid substitution type), ignoring, but please fix it.

**Comment by pelwell** [comment]
I wasn't expecting any substitution to happen in the command passed to /bin/sh, so ignoring the perceived error is the correct course of action. Perhaps there is a form of escaping that could be used to avoid the warning?

**Comment by XECDesign** [comment]
Ubuntu seems to have their own version of the package which is different from ours.

**Comment by mike-silva** [comment]
> Perhaps there is a form of escaping that could be used to avoid the warning?

It seems that the proper dash syntax is to use $$, where the rule is presently using a single $.

Given this is an Ubuntu issue, I'll report to them.
