### ISSUE TITLE
Can you please translate logic of script to human's?

### ISSUE THREAD

**Issue by ghost** [RPi-Distro/pi-bluetooth#6]
...

**Comment by pelwell** [comment]
Pi Zero W and Pi 3B+ have flow control signals connected to the Bluetooth modem, so they can run at 3000000 baud and flow. Without flow control we limit the baud rate to avoid overflow - ttyAMA0/UART0 has larger FIFOs so can be run at 921600 baud, whereas the less capable ttyS0/UART1 we limit to 460800 baud.
