### ISSUE TITLE
Could you commit your changes for version 0.1.11

### ISSUE THREAD

**Issue by rafaello7** [RPi-Distro/pi-bluetooth#9]
You have made changes for Raspberry Pi 4?

**Comment by pelwell** [comment]
What makes you think there are changes? You can compare the scripts in the repo against the current Raspbian images/packages yourself.

**Comment by rafaello7** [comment]
I have installed recently "Raspbian Full" and the _dpkg -l pi-bluetooth_ command shows version _0.1.11_. The [changelog](https://github.com/RPi-Distro/pi-bluetooth/blob/master/debian/changelog) on github has most recent version _0.1.10_. Also the _dpkg-buildpackage_ command invoked on my copy of this repo builts "deb" package version _0.1.10_.

I have checked the differences and I see some changes in _btuart_ script for "Pi 4":

    if grep -q "Pi 4" /proc/device-tree/model; then
      BDADDR=
    else
      SERIAL=`cat /proc/device-tree/serial-number | cut -c9-`
      B1=`echo $SERIAL | cut -c3-4`
      B2=`echo $SERIAL | cut -c5-6`
      B3=`echo $SERIAL | cut -c7-8`
      BDADDR=`printf b8:27:eb:%02x:%02x:%02x $((0x$B1 ^ 0xaa)) $((0x$B2 ^ 0xaa)) $((0x$B3 ^ 0xaa))`
    fi

The [btuart](https://github.com/RPi-Distro/pi-bluetooth/blob/master/usr/bin/btuart) on github does not contain the changes.

**Comment by XECDesign** [comment]
Changes pushed. Thanks.
